"""Run through Blender MCP execute_blender_code. Deterministic, original assets.
Keeps the starting scene, builds in a dedicated scene, exports Godot GLBs.
"""
import bpy, math
from pathlib import Path
from mathutils import Vector
BASE = Path('/home/clau/dev/space-ranger')
OUT = BASE / 'assets/models/eclipse_expansion'
OUT.mkdir(parents=True, exist_ok=True)
scene = bpy.data.scenes.get('Eclipse Expansion Atelier') or bpy.data.scenes.new('Eclipse Expansion Atelier')
bpy.context.window.scene = scene
# Rebuild only the atelier generated by this tool; leave the starting scene intact.
if scene.name == 'Eclipse Expansion Atelier':
    for o in list(scene.objects): bpy.data.objects.remove(o, do_unlink=True)

def mat(name, color, metal=0.7, rough=0.32, glow=0):
    m=bpy.data.materials.new(name); m.diffuse_color=(*color,1); m.use_nodes=True
    p=m.node_tree.nodes.get('Principled BSDF'); p.inputs['Base Color'].default_value=(*color,1)
    p.inputs['Metallic'].default_value=metal; p.inputs['Roughness'].default_value=rough
    if glow:
        p.inputs['Emission Color'].default_value=(*color,1); p.inputs['Emission Strength'].default_value=glow
    return m
DARK=mat('Eclipse | carbon ceramic',(0.025,0.045,0.065),.65,.4)
STEEL=mat('Eclipse | brushed titanium',(.28,.39,.46),.88,.26)
WHITE=mat('Eclipse | pearl armor',(.72,.83,.86),.45,.34)
GOLD=mat('Eclipse | rescue amber',(.95,.48,.09),.7,.3)
CYAN=mat('Eclipse | ion cyan',(.035,.8,1),.25,.24,3)
MINT=mat('Eclipse | cryo mint',(.08,1,.65),.25,.24,3)
PINK=mat('Eclipse | void orchid',(.7,.15,1),.3,.24,3)
RED=mat('Eclipse | hostile optics',(1,.08,.025),.25,.24,3)

def empty(name,pos=(0,0,0),parent=None):
    o=bpy.data.objects.new(name,None); scene.collection.objects.link(o); o.parent=parent; o.location=pos; return o

def finish(o,name,pos,size,material,parent=None):
    o.name=name; o.location=pos; o.scale=size
    bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
    o.data.materials.append(material)
    if o.type=='MESH':
        b=o.modifiers.new('Machined edge highlights','BEVEL'); b.width=.035; b.segments=2
        bpy.context.view_layer.objects.active=o; bpy.ops.object.modifier_apply(modifier=b.name)
        for poly in o.data.polygons: poly.use_smooth=True
        n=o.modifiers.new('Weighted plate normals','WEIGHTED_NORMAL')
        bpy.ops.object.modifier_apply(modifier=n.name)
    o.parent=parent
    return o

def box(name,pos,size,material,parent=None,rot=None):
    bpy.ops.mesh.primitive_cube_add(size=1)
    o=finish(bpy.context.object,name,pos,size,material,parent)
    if rot:o.rotation_euler=rot
    return o

def sphere(name,pos,size,material,parent=None):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=20,ring_count=12,radius=1)
    return finish(bpy.context.object,name,pos,size,material,parent)

def rod(name,a,b,r,material,parent=None):
    a,b=Vector(a),Vector(b); d=b-a
    bpy.ops.mesh.primitive_cylinder_add(vertices=16,radius=r,depth=d.length)
    o=finish(bpy.context.object,name,(a+b)/2,(1,1,1),material,parent)
    o.rotation_euler=d.to_track_quat('Z','Y').to_euler();return o

def ring(name,pos,radius,width,material,parent=None):
    bpy.ops.mesh.primitive_torus_add(major_segments=40,minor_segments=8,major_radius=radius,minor_radius=width)
    o=finish(bpy.context.object,name,pos,(1,1,1),material,parent)
    o.rotation_euler.x=math.pi/2;return o

def export(name,objects):
    bpy.context.view_layer.update()
    bpy.ops.object.select_all(action='DESELECT')
    for o in objects:
        if o.name in bpy.context.view_layer.objects: o.select_set(True)
    bpy.ops.export_scene.gltf(filepath=str(OUT/(name+'.glb')),export_format='GLB',use_selection=True,export_animations=True,export_animation_mode='NLA_TRACKS')
    print('EXPORTED',name,len(objects))

def descendants(root): return [root]+list(root.children_recursive)

def cleanup(objects):
    for o in objects:bpy.data.objects.remove(o,do_unlink=True)

def tint_material(m,color):
    m=m.copy();m.name='Eclipse restyle | '+m.name
    if not m.use_nodes:return m
    p=m.node_tree.nodes.get('Principled BSDF')
    if not p:return m
    p.inputs['Metallic'].default_value=.65;p.inputs['Roughness'].default_value=.32
    inp=p.inputs['Base Color']
    if inp.is_linked:
        old=inp.links[0].from_socket
        mix=m.node_tree.nodes.new('ShaderNodeMixRGB');mix.blend_type='MULTIPLY';mix.inputs[0].default_value=.72
        mix.inputs[2].default_value=(*color,1)
        m.node_tree.links.new(old,mix.inputs[1]);m.node_tree.links.new(mix.outputs[0],inp)
    else:inp.default_value=(*color,1)
    return m

# Retain every skeleton, clip, socket and named articulation on existing models.
for source,name,accent in [('player','ranger',(.26,.72,.85)),('campaign_bosses/apex','apex',(.34,.47,.65)),('campaign_bosses/warden','warden',(.37,.24,.64)),('campaign_bosses/seraph','seraph',(.74,.33,.13))]:
    before=set(bpy.data.objects);bpy.ops.import_scene.gltf(filepath=str(BASE/'assets/models'/(source+'.glb')))
    objects=set(bpy.data.objects)-before
    mats={m for o in objects if o.type=='MESH' for m in o.data.materials if m}
    remap={}
    for m in mats:
        lower=m.name.lower()
        if any(w in lower for w in ['optic','visor','reactor','ruby','core','conduit']):
            c=(.03,.75,1) if name=='ranger' else ((.8,.12,1) if name=='warden' else (1,.38,.06))
            mm=mat('Eclipse '+name+' luminous '+m.name,c,.35,.22,2)
        elif any(w in lower for w in ['carbon','joint','seal','cavit','tendon','undersuit']):continue
        else:mm=tint_material(m,accent)
        remap[m]=mm
    for o in objects:
        if o.type=='MESH':
            for i,m in enumerate(o.data.materials):
                if m in remap:o.data.materials[i]=remap[m]
    # The ranger's existing sculpted suit supplies fitted armor; avoid box overlays.
    if name=='apex':
        parent=next((o for o in objects if o.name.startswith('ShoulderRocketPod_L')),None)
        if parent:
            for i in range(3):
                o=box('Amber rank insignia',(-.22+i*.07,-.22,.1),(.04,.025,.14),GOLD,parent);objects.add(o)
    elif name=='warden':
        parent=next(o for o in objects if o.name.startswith('ColossusTorso'))
        for i in range(5):
            o=box('Amethyst dorsal reactor',(0,.25+i*.23,.58),(.12,.18,.35-i*.025),PINK,parent,rot=(0,.3,0));objects.add(o)
    elif name=='seraph':
        parent=next(o for o in objects if o.name.startswith('SeraphHead'))
        for side in [-1,1]:
            o=box('Swept solar crown',(side*.33,0,.28),(.08,.16,.52),GOLD,parent,rot=(0,side*.45,0));objects.add(o)
    export(name,objects);cleanup(objects)

# K-9 Cerberus: low profile quadruped, articulated legs and a dorsal rail weapon.
root=empty('Cerberus_K9')
box('Armored spine',(0,0,.81),(1.5,.5,.46),DARK,root)
box('Pearl back plating',(-.13,0,1.07),(1.12,.58,.15),WHITE,root)
for side in [-1,1]:
    box('Side amber identification',(-.15,side*.29,.85),(.63,.025,.08),GOLD,root)
    for x in [-.53,.48]:
        pivot=empty(('Front' if x>0 else 'Rear')+('_near' if side<0 else '_far'),(x,side*.3,.81),root)
        sphere('Exposed hip actuator',(0,0,0),(.14,.14,.14),STEEL,pivot)
        rod('Upper hydraulic leg',(0,0,0),(-.12,0,-.3),.07,STEEL,pivot)
        box('Knee shield',(-.12,0,-.27),(.22,.18,.2),WHITE,pivot)
        rod('Reverse joint shin',(-.12,0,-.3),(.06,0,-.64),.055,DARK,pivot)
        box('Magnetic paw',(.14,0,-.71),(.34,.21,.13),DARK,pivot)
head=empty('HoundHead',(.68,0,.91),root)
box('Wedge muzzle',(.25,0,0),(.56,.4,.24),WHITE,head)
box('Lower jaw',(.26,0,-.16),(.47,.32,.08),DARK,head)
for side in [-1,1]:
    box('Alert ear',(-.01,side*.17,.25),(.12,.09,.3),DARK,head,rot=(0,-.22,0))
    box('Predator optic',(.2,side*.205,.05),(.2,.025,.055),RED,head)
    for x in [.15,.32,.49]:box('Titanium tooth',(x,side*.14,-.11),(.05,.04,.065),STEEL,head)
rod('Segmented tail',(-.7,0,.9),(-1.13,0,1.14),.07,STEEL,root)
gun=empty('WeaponMount',(-.12,0,1.23),root)
box('Rail receiver',(0,0,0),(.65,.29,.2),DARK,gun)
for z in [-.09,.09]:
    rod('Rail barrel',(.1,z,0),(.83,z,0),.055,STEEL,gun)
    box('Ion rail strip',(.44,z,.055),(.65,.035,.025),RED,gun)
empty('Muzzle',(.9,0,0),gun)
export('hound',descendants(root));cleanup(descendants(root))

# Wasp interceptor: silhouette is a machine, distinct from the existing jetpack scout.
root=empty('Wasp_Interceptor')
sphere('Sensor carapace',(0,0,0),(.52,.3,.25),DARK,root)
box('Top shell',(-.1,0,.17),(.65,.48,.12),WHITE,root)
sphere('Forward optic',(.43,0,.03),(.14,.22,.13),RED,root)
for side in [-1,1]:
    box('Swept pylon',(-.08,side*.48,.02),(.55,.58,.09),STEEL,root,rot=(0,0,side*.25))
    rotor=empty('Rotor'+str(side),(-.15,side*.73,.02),root)
    r=ring('Ducted fan', (0,0,0),.26,.048,WHITE,rotor);r.rotation_euler.x=0
    for angle in [0,math.pi/2]:box('Fan blade',(0,0,0),(.45,.045,.03),DARK,rotor,rot=(0,0,angle))
    sphere('Ion thruster',(-.15,side*.73,-.08),(.14,.14,.08),CYAN,root)
    rod('Twin pulse barrel',(.04,side*.23,-.16),(.59,side*.23,-.16),.047,STEEL,root)
empty('Muzzle',(.64,0,-.16),root)
export('wasp',descendants(root));cleanup(descendants(root))

# Cryo Leviathan: hovering manta siege machine with animated nacelles.
root=empty('Cryo_Leviathan')
sphere('Armored manta hull',(0,0,0),(1.25,.62,.65),DARK,root)
for side in [-1,1]:
    box('Faceted glacier prow',(side*.73,-.2,.22),(1.12,.78,.55),WHITE,root,rot=(0,side*-.2,side*.12))
    box('Recessed intake',(side*.93,-.61,.12),(.55,.07,.19),DARK,root,rot=(0,side*-.2,0))
    for i in range(4):
        box('Intake grille',(side*.93+(i-1.5)*.11,-.655,.12),(.035,.035,.16),STEEL,root)
    box('Forward frost seam',(side*.76,-.615,.5),(.86,.035,.04),MINT,root,rot=(0,side*-.2,0))
    rod('Rear ion nacelle',(side*1.25,.35,0),(side*1.25,1.35,0),.26,STEEL,root)
    sphere('Thruster aperture',(side*1.25,1.37,0),(.19,.04,.19),MINT,root)
    box('Swept dorsal fin',(side*.55,.44,.85),(.14,.8,.64),DARK,root,rot=(.3,side*.35,0))
    box('Dorsal frost marking',(side*.55,.015,.85),(.065,.035,.42),MINT,root,rot=(0,side*.35,0))
for i in range(3):
    box('Central layered glacis',(0,.1+i*.26,.55-i*.06),(.64,.38,.18),STEEL,root)
    box('Service stripe',(0,-.1+i*.26,.64-i*.06),(.16,.04,.025),GOLD,root)
box('Central carbon keel',(0,-.58,-.08),(.65,.25,1.55),DARK,root)
ring('Cryo reactor aperture',(0,-.74,.15),.44,.075,STEEL,root)
sphere('CoreSocket',(0,-.8,.15),(.31,.08,.31),MINT,root)
for side in [-1,1]:
    wing=empty('SiegeWing'+str(side),(side*1.05,0,.15),root)
    for i in range(3):
        box('Manta layered wing',(side*(.4+i*.48),0,-i*.18),(.95,.8,.2),WHITE,wing,rot=(0,side*.18,0))
        box('Cryo light seam',(side*(.4+i*.48),-.28,-i*.18),(.7,.035,.045),MINT,wing)
    rod('Siege lance',(side*2.1,0,-.2),(side*2.1,0,-1.35),.19,STEEL,root)
    ring('Lance collar',(side*2.1,0,-.35),.22,.035,MINT,root).rotation_euler.x=0
    for i in range(4):
        box('Lance heatsink',(side*2.1,-.23,-.4-i*.18),(.3,.12,.075),DARK,root)
    for lateral in [-1,1]:
        box('Lance energy rail',(side*2.1+lateral*.17,0,-.85),(.055,.07,.8),MINT,root)
    empty('MuzzleLeft' if side<0 else 'MuzzleRight',(side*2.1,0,-1.38),root)
    for i in range(4):box('Frost radiator',(side*1.08,.38,.35-i*.2),(.45,.33,.07),DARK,root)
ring('ReactorRotor',(0,.15,.9),.72,.06,MINT,root)
export('leviathan',descendants(root));cleanup(descendants(root))

# Eclipse Sovereign: floating multi-ring eye, radial segmented armor and cannons.
root=empty('Eclipse_Sovereign')
sphere('Singularity chamber',(0,0,0),(.9,.65,.9),DARK,root)
ring('Inner gilded aperture',(0,-.65,0),.65,.10,GOLD,root)
sphere('CoreSocket',(0,-.74,0),(.42,.14,.42),PINK,root)
rotor=empty('ReactorRotor',(0,0,0),root)
ring('Orbital crown',(0,0,0),1.65,.075,GOLD,rotor)
for i in range(12):
    a=i*math.tau/12;x,z=math.sin(a),math.cos(a)
    box('Radial crown armor',(x*1.68,0,z*1.68),(.46,.42,.65),STEEL,rotor,rot=(0,a,0))
    box('Orchid crown rune',(x*1.7,-.235,z*1.7),(.12,.025,.37),PINK,rotor,rot=(0,a,0))
ring('Outer eclipse corona',(0,.25,0),2.4,.05,PINK,root)
for side in [-1,1]:
    box('Floating cannon housing',(side*2.48,0,-.85),(.65,.65,1.25),DARK,root)
    rod('Sovereign muzzle',(side*2.48,0,-1.05),(side*2.48,0,-1.9),.18,STEEL,root)
    sphere('Cannon power cell',(side*2.48,-.36,-.68),(.21,.08,.3),PINK,root)
    empty('MuzzleLeft' if side<0 else 'MuzzleRight',(side*2.48,0,-1.95),root)
export('sovereign',descendants(root));cleanup(descendants(root))

# Original scene props, reusable across the five biome palettes.
for name,glow in [('cryo_tower',MINT),('reactor_arch',CYAN),('void_obelisk',PINK)]:
    root=empty(name)
    if name=='reactor_arch':
        for side in [-1,1]:
            box('Portal pier',(side*3,0,3),(.65,.85,6),DARK,root)
            box('Pier ion inset',(side*3,-.45,3),(.09,.035,4.8),glow,root)
        box('Truss lintel',(0,0,6),(6.7,.85,.6),STEEL,root)
        for i in range(7):box('Amber chevron',(-2.4+i*.8,-.45,6),(.3,.04,.25),GOLD,root,rot=(0,.35,0))
    elif name=='cryo_tower':
        box('Cooling base',(0,0,.25),(1.9,1.9,.5),DARK,root)
        rod('Cryo reservoir',(0,0,.5),(0,0,4.5),.7,WHITE,root)
        for i in range(7):
            r=ring('Heat exchanger',(0,0,.8+i*.55),.84,.055,STEEL,root);r.rotation_euler.x=0
        for side in [-1,1]:box('Coolant inspection strip',(side*.4,-.59,2.5),(.1,.08,3.4),glow,root)
        sphere('Coolant cap',(0,0,4.65),(.63,.63,.25),glow,root)
    else:
        box('Plinth',(0,0,.2),(2,1.5,.4),DARK,root)
        box('Suspended monolith',(0,0,2.8),(1,.8,4.5),STEEL,root,rot=(0,.15,0))
        box('Void aperture',(0,-.44,2.8),(.16,.05,3.6),glow,root,rot=(0,.15,0))
        ring('Orbital seal',(0,-.5,3),1.3,.045,GOLD,root)
    export(name,descendants(root));cleanup(descendants(root))
# Save a source workbench containing all authored exports arranged in a gallery.
for i,name in enumerate(['ranger','apex','warden','seraph','hound','wasp','leviathan','sovereign','cryo_tower','reactor_arch','void_obelisk']):
    before=set(bpy.data.objects);bpy.ops.import_scene.gltf(filepath=str(OUT/(name+'.glb')))
    for o in set(bpy.data.objects)-before:
        if o.parent is None:o.location.x+=i*9
bpy.data.libraries.write(str(OUT/'eclipse_atelier.blend'), {scene}, fake_user=True, compress=True)
print('ECLIPSE EXPANSION COMPLETE')
